insert into public.finance_entries (
  company_id,
  account_id,
  category_id,
  activity_id,
  cost_center_id,
  entry_type,
  title,
  description,
  document_type,
  document_number,
  amount,
  currency_code,
  status,
  payment_method,
  issue_date,
  due_date,
  settlement_date,
  competence_date,
  company_unit,
  vendor_name,
  customer_name,
  tags,
  metadata,
  created_by,
  updated_by
)
select
  p.id as company_id,
  acc.id as account_id,
  cat.id as category_id,
  act.id as activity_id,
  cc.id as cost_center_id,
  seed.entry_type,
  seed.title,
  seed.description,
  seed.document_type,
  seed.document_number,
  seed.amount,
  'BRL' as currency_code,
  seed.status,
  seed.payment_method,
  seed.issue_date,
  seed.due_date,
  seed.settlement_date,
  seed.competence_date,
  seed.company_unit,
  seed.vendor_name,
  seed.customer_name,
  seed.tags,
  seed.metadata::jsonb,
  p.id as created_by,
  p.id as updated_by
from public.profiles p
join lateral (
  values
    (
      'income'::text,
      'Receita de contrato empresarial'::text,
      'Entrada de contrato comercial da Aurora'::text,
      'invoice'::text,
      'NF-2026-1001'::text,
      8900.00::numeric,
      'received'::text,
      'Transferência bancária'::text,
      date '2026-03-18',
      date '2026-03-30',
      date '2026-03-30',
      date '2026-03-01',
      'Unidade principal'::text,
      null::text,
      'Cliente empresarial Aurora'::text,
      array['receita','contrato']::text[],
      '{"source":"seed","kind":"income"}'::text,
      'Receitas'::text,
      'Contrato empresarial'::text,
      'Banco principal'::text,
      'Vendas'::text
    ),
    (
      'expense'::text,
      'Frete local operacional'::text,
      'Saída com frete de apoio local'::text,
      'receipt'::text,
      'REC-2026-2001'::text,
      920.00::numeric,
      'approved'::text,
      'PIX'::text,
      date '2026-03-25',
      date '2026-03-28',
      null::date,
      date '2026-03-01',
      'Base sul'::text,
      'Fornecedor Logístico Local'::text,
      null::text,
      array['frete','logistica']::text[],
      '{"source":"seed","kind":"expense"}'::text,
      'Logística'::text,
      'Frete local'::text,
      'PIX principal'::text,
      'Logística'::text
    ),
    (
      'expense'::text,
      'Comissão interna comercial'::text,
      'Comissão por fechamento de contrato'::text,
      'contract'::text,
      'COM-2026-017'::text,
      1350.00::numeric,
      'paid'::text,
      'Transferência bancária'::text,
      date '2026-03-20',
      date '2026-03-25',
      date '2026-03-25',
      date '2026-03-01',
      'Unidade principal'::text,
      'Equipe comercial interna'::text,
      null::text,
      array['comissao','comercial']::text[],
      '{"source":"seed","kind":"expense"}'::text,
      'Comercial'::text,
      'Comissão interna'::text,
      'Banco principal'::text,
      'Vendas'::text
    ),
    (
      'expense'::text,
      'Caixa viagem operacional'::text,
      'Controle de caixa de viagem da operação'::text,
      'internal_note'::text,
      'CXV-2026-001'::text,
      480.00::numeric,
      'open'::text,
      'Dinheiro'::text,
      date '2026-03-30',
      date '2026-04-01',
      null::date,
      date '2026-03-01',
      'Unidade principal'::text,
      'Operação externa'::text,
      null::text,
      array['caixa','viagem']::text[],
      '{"source":"seed","kind":"expense"}'::text,
      'Operações'::text,
      'Caixa viagem'::text,
      'Caixa'::text,
      'Operação externa'::text
    ),
    (
      'expense'::text,
      'Custo operacional administrativo'::text,
      'Saída administrativa de apoio operacional'::text,
      'service_order'::text,
      'OS-2026-3301'::text,
      610.00::numeric,
      'pending'::text,
      'Boleto'::text,
      date '2026-03-29',
      date '2026-04-05',
      null::date,
      date '2026-03-01',
      'Administrativo'::text,
      'Prestador administrativo'::text,
      null::text,
      array['administrativo','custo']::text[],
      '{"source":"seed","kind":"expense"}'::text,
      'Administrativo'::text,
      'Custo operacional'::text,
      'Banco principal'::text,
      'Administrativo'::text
    )
) as seed(
  entry_type,
  title,
  description,
  document_type,
  document_number,
  amount,
  status,
  payment_method,
  issue_date,
  due_date,
  settlement_date,
  competence_date,
  company_unit,
  vendor_name,
  customer_name,
  tags,
  metadata,
  category_name,
  activity_name,
  account_name,
  cost_center_name
) on true
left join public.finance_categories cat
  on cat.company_id = p.id
 and lower(cat.name) = lower(seed.category_name)
left join public.finance_activities act
  on act.company_id = p.id
 and lower(act.name) = lower(seed.activity_name)
left join public.finance_accounts acc
  on acc.company_id = p.id
 and lower(acc.name) = lower(seed.account_name)
left join public.finance_cost_centers cc
  on cc.company_id = p.id
 and lower(cc.name) = lower(seed.cost_center_name)
where not exists (
  select 1
  from public.finance_entries fe
  where fe.company_id = p.id
    and fe.document_number = seed.document_number
);